[en]
  title = "CHaf's Blog"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[zh]
  title = "Chaf's 博客"
  languageName = "简体中文"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/zh"
